package recyclingservice;

import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adamp
 */
public class SubPriceUI extends javax.swing.JFrame {
    Subscriptions S = new Subscriptions();
    int input;
    /**
     * Creates new form SubPriceUI
     */
    public SubPriceUI() {
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorJPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        BalanceBtn = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        headingLabel1 = new javax.swing.JLabel();
        bronzeBtn = new javax.swing.JButton();
        silverBtn = new javax.swing.JButton();
        goldBtn = new javax.swing.JButton();
        yearlyCostLabel = new javax.swing.JLabel();
        yearlyCostChangingLabel = new javax.swing.JLabel();
        monthlyCostBtn = new javax.swing.JLabel();
        monthlyCostChangingLabel = new javax.swing.JLabel();
        subChooserLabel = new javax.swing.JLabel();
        subTextField = new javax.swing.JTextField();
        purchaseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        colorJPanel.setBackground(new java.awt.Color(111, 162, 202));

        javax.swing.GroupLayout colorJPanelLayout = new javax.swing.GroupLayout(colorJPanel);
        colorJPanel.setLayout(colorJPanelLayout);
        colorJPanelLayout.setHorizontalGroup(
            colorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );
        colorJPanelLayout.setVerticalGroup(
            colorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homeBtn.setBackground(new java.awt.Color(30, 30, 30));
        homeBtn.setForeground(new java.awt.Color(111, 162, 202));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        BalanceBtn.setBackground(new java.awt.Color(30, 30, 30));
        BalanceBtn.setForeground(new java.awt.Color(111, 162, 202));
        BalanceBtn.setText("Balance");
        BalanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceBtnActionPerformed(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(111, 162, 202));
        headingLabel.setText("Subscription Price Calculator");

        headingLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        headingLabel1.setForeground(new java.awt.Color(111, 162, 202));
        headingLabel1.setText("Click one the buttons to show the monthly & yearly cost");

        bronzeBtn.setBackground(new java.awt.Color(30, 30, 30));
        bronzeBtn.setForeground(new java.awt.Color(111, 162, 202));
        bronzeBtn.setText("Bronze Subscription");
        bronzeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bronzeBtnActionPerformed(evt);
            }
        });

        silverBtn.setBackground(new java.awt.Color(30, 30, 30));
        silverBtn.setForeground(new java.awt.Color(111, 162, 202));
        silverBtn.setText("Silver Subscription");
        silverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silverBtnActionPerformed(evt);
            }
        });

        goldBtn.setBackground(new java.awt.Color(30, 30, 30));
        goldBtn.setForeground(new java.awt.Color(111, 162, 202));
        goldBtn.setText("Gold Subscription");
        goldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldBtnActionPerformed(evt);
            }
        });

        yearlyCostLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        yearlyCostLabel.setForeground(new java.awt.Color(111, 162, 202));
        yearlyCostLabel.setText("Yearly Subscription Cost:");

        yearlyCostChangingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        yearlyCostChangingLabel.setForeground(new java.awt.Color(111, 162, 202));

        monthlyCostBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        monthlyCostBtn.setForeground(new java.awt.Color(111, 162, 202));
        monthlyCostBtn.setText("Monthly Subscription Cost:");

        monthlyCostChangingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        monthlyCostChangingLabel.setForeground(new java.awt.Color(111, 162, 202));

        subChooserLabel.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        subChooserLabel.setForeground(new java.awt.Color(111, 162, 202));
        subChooserLabel.setText("Enter the Subcription you would like to purchase");

        subTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTextFieldActionPerformed(evt);
            }
        });

        purchaseBtn.setBackground(new java.awt.Color(30, 30, 30));
        purchaseBtn.setForeground(new java.awt.Color(111, 162, 202));
        purchaseBtn.setText("Purchase");
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(yearlyCostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(monthlyCostBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monthlyCostChangingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearlyCostChangingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(headingLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bronzeBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(silverBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(goldBtn)))
                                .addGap(104, 104, 104))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(homeBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BalanceBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(headingLabel)))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(subChooserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purchaseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(colorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn)
                    .addComponent(BalanceBtn))
                .addGap(23, 23, 23)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headingLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bronzeBtn)
                    .addComponent(silverBtn)
                    .addComponent(goldBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthlyCostBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthlyCostChangingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearlyCostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlyCostChangingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subChooserLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purchaseBtn))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        dispose();
        HomePage HP = new HomePage();
        HP.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        if(subTextField.getText().equalsIgnoreCase("Bronze")){
           if(S.ShowBalance() <= 29){
               JOptionPane.showMessageDialog(null, "You do not have enough funds to purchase the Bronze subscription. Please top up your balance to proceed with the purchase.");
           }
           else{
                S.BronzePurchase();
                JOptionPane.showMessageDialog(null, "You have just purchased the Bronze Subscription");
           }
        }else if(subTextField.getText().equalsIgnoreCase("Silver")){
           if(S.ShowBalance() <= 49){
               JOptionPane.showMessageDialog(null, "You do not have enough funds to purchase the Silver subscription. Please top up your balance to proceed with the purchase.");
           }else{
                S.SilverPurchase();
                JOptionPane.showMessageDialog(null, "You have just purchased the Silver Subscription");
           }
        }
        else if(subTextField.getText().equalsIgnoreCase("Gold")){
           if(S.ShowBalance() <= 79){
            JOptionPane.showMessageDialog(null, "You do not have enough funds to purchase the Gold subscription. Please top up your balance to proceed with the purchase.");
           }
           else{
               S.GoldPurchase();
               JOptionPane.showMessageDialog(null, "You have just purchased the Gold Subscription");       
           }  
        }
    }//GEN-LAST:event_purchaseBtnActionPerformed

    private void bronzeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bronzeBtnActionPerformed
        int temp = S.ComputeBronze();
        monthlyCostChangingLabel.setText("€30");
        yearlyCostChangingLabel.setText("€"+String.valueOf(temp));
        JOptionPane.showMessageDialog(null, "For the Bronze Subscription, you get:\n- Our premium recycling bin service");
    }//GEN-LAST:event_bronzeBtnActionPerformed

    private void silverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silverBtnActionPerformed
        int temp = S.ComputeSilver();
        monthlyCostChangingLabel.setText("€50");
        yearlyCostChangingLabel.setText("€"+String.valueOf(temp));
        JOptionPane.showMessageDialog(null, "For the Silver Subscription, you get:\n- Our premium recycling bin service\n- Wide variety of recycling options");
    }//GEN-LAST:event_silverBtnActionPerformed

    private void goldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldBtnActionPerformed
        int temp = S.ComputeGold();
        monthlyCostChangingLabel.setText("€80");
        yearlyCostChangingLabel.setText("€"+String.valueOf(temp));
        JOptionPane.showMessageDialog(null, "For the Gold Subscription, you get:\n- Our premium recycling bin service\n- Wide variety of recycling options\n- Adjustable bin collecting timeframe,\n  set for when it's most conveintent for you");
    }//GEN-LAST:event_goldBtnActionPerformed

    private void subTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTextFieldActionPerformed

    }//GEN-LAST:event_subTextFieldActionPerformed

    private void BalanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceBtnActionPerformed
        int ans = Integer.parseInt(JOptionPane.showInputDialog(null,"Press the number shown to:\n1) Add Balance\n2) Subtract Balance\n3) View Balance"));
        switch(ans){
            case 1 : input = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter the amount you would like to add to your account."));
                     S.setBalance(input);
                     S.AddBalance();
                     JOptionPane.showMessageDialog(null,"You added €"+input+" to your account."+"\nYou have €"+S.ShowBalance()+" in your account currently.");
                break;
            case 2 : input = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter the amount you would like to subtract from your account."));
                     S.setBalance(input);
                     S.SubBalance();
                     if(S.ShowBalance() >= 1){
                         JOptionPane.showMessageDialog(null,"You removed €"+input+" to your account."+"\nYou now have €"+S.ShowBalance()+" in your account currently.");
                     }else if(S.ShowBalance() == 0){
                        JOptionPane.showMessageDialog(null, "You do not have anything in your account to remove. Please top up.");
                     }
                break;
            case 3 : JOptionPane.showMessageDialog(null,"You have €"+S.ShowBalance()+" in your account currently.");
                break;
            default: if(ans != 1 || ans != 2 || ans != 3){JOptionPane.showMessageDialog(null, "Please only enter a number shown.");}
        }
    }//GEN-LAST:event_BalanceBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubPriceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubPriceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubPriceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubPriceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubPriceUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BalanceBtn;
    private javax.swing.JButton bronzeBtn;
    private javax.swing.JPanel colorJPanel;
    private javax.swing.JButton goldBtn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel headingLabel1;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel monthlyCostBtn;
    private javax.swing.JLabel monthlyCostChangingLabel;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JButton silverBtn;
    private javax.swing.JLabel subChooserLabel;
    private javax.swing.JTextField subTextField;
    private javax.swing.JLabel yearlyCostChangingLabel;
    private javax.swing.JLabel yearlyCostLabel;
    // End of variables declaration//GEN-END:variables
}
