package recyclingservice;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adamp
 */
public class UserSignUpUI extends javax.swing.JFrame {
    private ArrayList <UserDetails> Accounts;
    private String name, email, address, phone, password;
    private int count;
    /**
     * Creates new form UserSignUp
     */
    public UserSignUpUI() {
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 30));
        pwUnhiderRBtn.setBackground(new Color(30, 30, 30));
        Accounts = new ArrayList<>();
        name = new String();
        email = new String();
        address = new String();
        phone = new String();
        password = new String();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorJPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        searchAccountBtn = new javax.swing.JButton();
        headingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        pwUnhiderRBtn = new javax.swing.JRadioButton();
        changingLabel = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        deleteLabel = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        subCalcBtn = new javax.swing.JButton();
        deleteLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Sign Up page");
        setBackground(new java.awt.Color(246, 246, 246));
        setResizable(false);

        colorJPanel.setBackground(new java.awt.Color(111, 162, 202));

        javax.swing.GroupLayout colorJPanelLayout = new javax.swing.GroupLayout(colorJPanel);
        colorJPanel.setLayout(colorJPanelLayout);
        colorJPanelLayout.setHorizontalGroup(
            colorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );
        colorJPanelLayout.setVerticalGroup(
            colorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        homeBtn.setBackground(new java.awt.Color(30, 30, 30));
        homeBtn.setForeground(new java.awt.Color(111, 162, 202));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        searchAccountBtn.setBackground(new java.awt.Color(30, 30, 30));
        searchAccountBtn.setForeground(new java.awt.Color(111, 162, 202));
        searchAccountBtn.setText("Search Account");
        searchAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAccountBtnActionPerformed(evt);
            }
        });

        headingLabel.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(111, 162, 202));
        headingLabel.setText("Account Creation");

        nameLabel.setForeground(new java.awt.Color(111, 162, 202));
        nameLabel.setText("Name");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        emailLabel.setForeground(new java.awt.Color(111, 162, 202));
        emailLabel.setText("Email");

        addressLabel.setForeground(new java.awt.Color(111, 162, 202));
        addressLabel.setText("Address");

        phoneLabel.setForeground(new java.awt.Color(111, 162, 202));
        phoneLabel.setText("Phone");

        passwordLabel.setForeground(new java.awt.Color(111, 162, 202));
        passwordLabel.setText("Password");

        pwUnhiderRBtn.setForeground(new java.awt.Color(111, 162, 202));
        pwUnhiderRBtn.setText("Unhide");
        pwUnhiderRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwUnhiderRBtnActionPerformed(evt);
            }
        });

        changingLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        changingLabel.setForeground(new java.awt.Color(111, 162, 202));

        signUpBtn.setBackground(new java.awt.Color(30, 30, 30));
        signUpBtn.setForeground(new java.awt.Color(111, 162, 202));
        signUpBtn.setText("Create Account");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        displayBtn.setBackground(new java.awt.Color(30, 30, 30));
        displayBtn.setForeground(new java.awt.Color(111, 162, 202));
        displayBtn.setText("Display Account(s)");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        deleteLabel.setForeground(new java.awt.Color(111, 162, 202));
        deleteLabel.setText("Enter your account details to delete the account you desire.");

        deleteBtn.setBackground(new java.awt.Color(30, 30, 30));
        deleteBtn.setForeground(new java.awt.Color(111, 162, 202));
        deleteBtn.setText("Delete Account");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        subCalcBtn.setBackground(new java.awt.Color(30, 30, 30));
        subCalcBtn.setForeground(new java.awt.Color(111, 162, 202));
        subCalcBtn.setText("Subscription Calculator");
        subCalcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCalcBtnActionPerformed(evt);
            }
        });

        deleteLabel1.setForeground(new java.awt.Color(111, 162, 202));
        deleteLabel1.setText("Click here to view our prices, and purchase a subscription.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deleteLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subCalcBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deleteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteBtn)
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(searchAccountBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(homeBtn)
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(emailLabel)
                                            .addComponent(nameLabel))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(nameTextField))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(signUpBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(phoneLabel)
                                            .addComponent(addressLabel)
                                            .addComponent(passwordLabel))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(phoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(addressTextField)
                                            .addComponent(passwordTextField))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(displayBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(pwUnhiderRBtn)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(changingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(colorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBtn)
                    .addComponent(displayBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchAccountBtn)
                .addGap(24, 24, 24)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailLabel)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLabel))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwUnhiderRBtn))
                .addGap(7, 7, 7)
                .addComponent(signUpBtn)
                .addGap(18, 18, 18)
                .addComponent(changingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(deleteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subCalcBtn)
                    .addComponent(deleteLabel1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        if(nameTextField.getText().equals("") || emailTextField.getText().equals("") || addressTextField.getText().equals("") || phoneTextField.getText().equals("") || passwordTextField.getText().equals("")){
            changingLabel.setText("You must enter your full details to make an account");   
        }
        else if(nameTextField.getText() != "" && emailTextField.getText()!= "" && addressTextField.getText()!= "" && phoneTextField.getText()!= "" && passwordTextField.getText()!= ""){
            name = nameTextField.getText();
            email = emailTextField.getText(); 
            address = addressTextField.getText(); 
            phone = phoneTextField.getText(); 
            password = passwordTextField.getText(); 

            UserDetails user = new UserDetails();
            user.setName(name);
            user.setEmail(email);
            user.setAddress(address);
            user.setPhone(phone);
            user.setPassword(password);

            Accounts.add(user);
            count++;
            changingLabel.setText("Your account has been created!");
        }
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed

    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        dispose();
        HomePage HP = new HomePage();
        HP.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        if(Accounts.size() == 0){
            changingLabel.setText("There are no accounts created to view");
        }
        for(int i=0; i < Accounts.size(); i++){
            JOptionPane.showMessageDialog(null, "Here are your account(s) details."+"\n Name: "+Accounts.get(i).getName()+"\n Email: "+Accounts.get(i).getEmail()+"\n Address: "+Accounts.get(i).getAddress()+"\n Phone: "+Accounts.get(i).getPhone());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(nameTextField.getText().equals("") || emailTextField.getText().equals("") || addressTextField.getText().equals("") || phoneTextField.getText().equals("") || passwordTextField.getText().equals("")){
            changingLabel.setText("You must first create an account");
        }
        else if(count == 0){
            changingLabel.setText("There are no accounts to delete");
        }
        else{
            name = nameTextField.getText();
            email = emailTextField.getText(); 
            address = addressTextField.getText(); 
            phone = phoneTextField.getText(); 
            password = passwordTextField.getText(); 
            
            for(int i=0; i < Accounts.size(); i++){
                if(Accounts.get(i).getName().equals(name)&& Accounts.get(i).getEmail().equals(email)&& Accounts.get(i).getAddress().equals(address)&& Accounts.get(i).getPhone().equals(phone)&&Accounts.get(i).getPassword().equals(password)){
                    Accounts.remove(i);
                    count = count - 1;
                    changingLabel.setText("Account User "+i+" Successfully Deleted.");
                    break;
                }
                if(count - 1 == i){
                    changingLabel.setText("That account could not be found.");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void subCalcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCalcBtnActionPerformed
        dispose();
        SubPriceUI UI = new SubPriceUI();
        UI.setVisible(true);
    }//GEN-LAST:event_subCalcBtnActionPerformed

    private void searchAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAccountBtnActionPerformed
        
        String search = JOptionPane.showInputDialog(null, "Please enter your account password");
        for(int i=0; i < Accounts.size(); i++){ 
            if(search.equalsIgnoreCase(Accounts.get(i).getPassword())){
                JOptionPane.showMessageDialog(null, "Here are your account(s) details."+"\n Name: "+Accounts.get(i).getName()+"\n Email: "+Accounts.get(i).getEmail()+"\n Address: "+Accounts.get(i).getAddress()+"\n Phone: "+Accounts.get(i).getPhone()+"\n Password: "+Accounts.get(i).getPassword());
            }
        }
    }//GEN-LAST:event_searchAccountBtnActionPerformed

    private void pwUnhiderRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwUnhiderRBtnActionPerformed
        if(pwUnhiderRBtn.isSelected()){
            passwordTextField.setEchoChar((char)0);
        }else{
             passwordTextField.setEchoChar('*');
        }
    }//GEN-LAST:event_pwUnhiderRBtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUpUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel changingLabel;
    private javax.swing.JPanel colorJPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JLabel deleteLabel1;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JRadioButton pwUnhiderRBtn;
    private javax.swing.JButton searchAccountBtn;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JButton subCalcBtn;
    // End of variables declaration//GEN-END:variables
}
