package recyclingservice;


import recyclingservice.UserSignUp;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adamp
 */
public class UserQuestion extends javax.swing.JFrame {

    /**
     * Creates new form UserQuestion
     */
    public UserQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecyclingServiceInfo = new javax.swing.JLabel();
        RecyclingServiceInfo2 = new javax.swing.JLabel();
        RecyclingServiceInfo3 = new javax.swing.JLabel();
        RecyclingServiceInfo4 = new javax.swing.JLabel();
        RecyclingServiceInfo5 = new javax.swing.JLabel();
        RecyclingServiceInfo6 = new javax.swing.JLabel();
        noBtn = new javax.swing.JButton();
        yesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Question");
        setBackground(new java.awt.Color(108, 174, 235));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));

        RecyclingServiceInfo.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RecyclingServiceInfo.setText("Not recycling properly can create huge global problems, such as global warming, deforestation, sea pollution and so on. ");

        RecyclingServiceInfo2.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo2.setText("At \"comp name\" we make it our mission to bring a reliable, affordable and straight forward recycling service to your door.");

        RecyclingServiceInfo3.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo3.setText("If this sounds appealing, you can create an account with us which will put you on our service list for a monthly price.");

        RecyclingServiceInfo4.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo4.setText("If you ever change your mind, you can delete your account which will take you off our subcription list and our services.");

        RecyclingServiceInfo5.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo5.setText("This will give your our premium service, filled with a wide variety of recycling options compared to other companies. ");

        RecyclingServiceInfo6.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo6.setText("If you would like to create an account click \"Yes\" if not click \"No\" which will bring you back to our main page.");

        noBtn.setText("No");

        yesBtn.setText("Yes");
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Recycling Service Subscription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecyclingServiceInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo)
                            .addComponent(RecyclingServiceInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo5, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo6, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(noBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        dispose();
        UserSignUp userSignUpUI = new UserSignUp();
        userSignUpUI.setVisible(true);
        
    }//GEN-LAST:event_yesBtnActionPerformed
    private void noBtnActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserQuestion userQuestionUI = new UserQuestion();
                userQuestionUI.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RecyclingServiceInfo;
    private javax.swing.JLabel RecyclingServiceInfo2;
    private javax.swing.JLabel RecyclingServiceInfo3;
    private javax.swing.JLabel RecyclingServiceInfo4;
    private javax.swing.JLabel RecyclingServiceInfo5;
    private javax.swing.JLabel RecyclingServiceInfo6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton noBtn;
    private javax.swing.JButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
