/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recyclingservice;

import java.awt.Color;
import recyclingservice.HomePage;

/**
 *
 * @author TOSHIBA
 */
public class goalsGUI extends javax.swing.JFrame {

    /**
     * Creates new form goalsGUI
     */
    public goalsGUI() {
        initComponents();
        getContentPane().setBackground(new Color(30,30,30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DailyBG = new javax.swing.ButtonGroup();
        Title = new javax.swing.JLabel();
        deadlineTF = new javax.swing.JTextField();
        deadline = new javax.swing.JLabel();
        tagetamount = new javax.swing.JLabel();
        targetamountTF = new javax.swing.JTextField();
        currentamount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        material = new javax.swing.JTextField();
        DailyRB = new javax.swing.JRadioButton();
        WeeklyRB = new javax.swing.JRadioButton();
        MonthlyRB = new javax.swing.JRadioButton();
        homeButton = new javax.swing.JButton();
        Motto = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        goal1 = new javax.swing.JLabel();
        goal2 = new javax.swing.JLabel();
        goal3 = new javax.swing.JLabel();
        currentamountFT = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));
        setPreferredSize(new java.awt.Dimension(850, 600));
        setResizable(false);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Title.setForeground(new Color (111, 162, 202));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("RECYCLING GOALS");

        deadline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deadline.setForeground(new Color (111, 162, 202));
        deadline.setText("DEADLINE:");

        tagetamount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tagetamount.setForeground(new Color (111, 162, 202));
        tagetamount.setText("TARGET AMOUNT:");

        targetamountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetamountTFActionPerformed(evt);
            }
        });

        currentamount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currentamount.setForeground(new Color (111, 162, 202));
        currentamount.setText("CURRENT AMOUNT:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new Color (111, 162, 202));
        jLabel1.setText("MATERIAL:");

        material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialActionPerformed(evt);
            }
        });

        DailyBG.add(DailyRB);
        DailyRB.setForeground(new Color (111, 162, 202));
        DailyRB.setText("Daily");
        DailyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DailyRBActionPerformed(evt);
            }
        });

        DailyBG.add(WeeklyRB);
        WeeklyRB.setForeground(new Color (111, 162, 202));
        WeeklyRB.setText("Weekly");
        WeeklyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeeklyRBActionPerformed(evt);
            }
        });

        DailyBG.add(MonthlyRB);
        MonthlyRB.setForeground(new Color (111, 162, 202));
        MonthlyRB.setText("Monthly");
        MonthlyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthlyRBActionPerformed(evt);
            }
        });

        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        Motto.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Motto.setForeground(new Color (111, 162, 202));
        Motto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Motto.setText("upcycle, reduce and recycle");

        goal1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goal1.setForeground(new Color (111, 162, 202));
        goal1.setText("GOAL 1:");

        goal2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goal2.setForeground(new Color (111, 162, 202));
        goal2.setText("GOAL 2:");

        goal3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goal3.setForeground(new Color (111, 162, 202));
        goal3.setText("GOAL 3:");

        currentamountFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentamountFTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(deadline)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(deadlineTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goal3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(currentamount)
                                    .addComponent(tagetamount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(targetamountTF)
                                    .addComponent(currentamountFT, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goal2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(goal1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DailyRB)
                            .addComponent(WeeklyRB)
                            .addComponent(MonthlyRB))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Motto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(homeButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(Title)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deadlineTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DailyRB)
                            .addComponent(deadline))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WeeklyRB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tagetamount)
                            .addComponent(targetamountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonthlyRB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentamount)
                            .addComponent(currentamountFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goal1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goal2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goal3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(Motto)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void targetamountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetamountTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetamountTFActionPerformed

    private void materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialActionPerformed

    private void DailyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DailyRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DailyRBActionPerformed

    private void MonthlyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthlyRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthlyRBActionPerformed

    private void WeeklyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeklyRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeeklyRBActionPerformed

    private void currentamountFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentamountFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentamountFTActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
       dispose();
       HomePage HPUI = new HomePage();
       HPUI.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(goalsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(goalsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(goalsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(goalsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new goalsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup DailyBG;
    private javax.swing.JRadioButton DailyRB;
    private javax.swing.JRadioButton MonthlyRB;
    private javax.swing.JLabel Motto;
    private javax.swing.JLabel Title;
    private javax.swing.JRadioButton WeeklyRB;
    private javax.swing.JLabel currentamount;
    private javax.swing.JFormattedTextField currentamountFT;
    private javax.swing.JLabel deadline;
    private javax.swing.JTextField deadlineTF;
    private javax.swing.JLabel goal1;
    private javax.swing.JLabel goal2;
    private javax.swing.JLabel goal3;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JTextField material;
    private javax.swing.JLabel tagetamount;
    private javax.swing.JTextField targetamountTF;
    // End of variables declaration//GEN-END:variables
}
