package recyclingservice;


import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author adamp
 */
public class UserQuestionUI extends javax.swing.JFrame {

    /**
     * Creates new form UserQuestion
     */
    public UserQuestionUI() {
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecyclingServiceInfo = new javax.swing.JLabel();
        RecyclingServiceInfo2 = new javax.swing.JLabel();
        RecyclingServiceInfo3 = new javax.swing.JLabel();
        RecyclingServiceInfo4 = new javax.swing.JLabel();
        RecyclingServiceInfo5 = new javax.swing.JLabel();
        RecyclingServiceInfo6 = new javax.swing.JLabel();
        noBtn = new javax.swing.JButton();
        yesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Question");
        setBackground(new java.awt.Color(108, 174, 235));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));

        RecyclingServiceInfo.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RecyclingServiceInfo.setForeground(new java.awt.Color(111, 162, 202));
        RecyclingServiceInfo.setText("Not recycling properly can create huge global problems, such as global warming, deforestation, sea pollution and so on. ");

        RecyclingServiceInfo2.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo2.setForeground(new java.awt.Color(111, 162, 202));
        RecyclingServiceInfo2.setText("At DADA Recycling we make it our mission to bring a reliable, affordable and straight forward recycling service to your door.");

        RecyclingServiceInfo3.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo3.setForeground(new java.awt.Color(111, 162, 202));
        RecyclingServiceInfo3.setText("If this sounds appealing, you can create an account with us which will put you on our service list for a monthly price.");

        RecyclingServiceInfo4.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo4.setForeground(new java.awt.Color(111, 162, 202));
        RecyclingServiceInfo4.setText("If you ever change your mind, you can delete your account which will take you off our subcription list and our services.");

        RecyclingServiceInfo5.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo5.setForeground(new java.awt.Color(111, 162, 202));
        RecyclingServiceInfo5.setText("This will give your our premium service, filled with a wide variety of recycling options compared to other companies. ");

        RecyclingServiceInfo6.setBackground(new java.awt.Color(110, 174, 233));
        RecyclingServiceInfo6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecyclingServiceInfo6.setForeground(new java.awt.Color(111, 162, 202));
        RecyclingServiceInfo6.setText("If you would like to create an account click \"Yes\" if not click \"No\" which will bring you back to our main page.");

        noBtn.setBackground(new java.awt.Color(30, 30, 30));
        noBtn.setForeground(new java.awt.Color(111, 162, 202));
        noBtn.setText("No");
        noBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBtnActionPerformed(evt);
            }
        });

        yesBtn.setBackground(new java.awt.Color(30, 30, 30));
        yesBtn.setForeground(new java.awt.Color(111, 162, 202));
        yesBtn.setText("Yes");
        yesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(111, 162, 202));
        jLabel1.setText("Recycling Service Subscription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RecyclingServiceInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo)
                            .addComponent(RecyclingServiceInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo5, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecyclingServiceInfo6, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(noBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecyclingServiceInfo6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBtnActionPerformed
        dispose();
        UserSignUpUI userSignUpUI = new UserSignUpUI();
        userSignUpUI.setVisible(true);
        
    }//GEN-LAST:event_yesBtnActionPerformed

    private void noBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBtnActionPerformed
        dispose();
        HomePage HPUI = new HomePage();
        HPUI.setVisible(true);
    }//GEN-LAST:event_noBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RecyclingServiceInfo;
    private javax.swing.JLabel RecyclingServiceInfo2;
    private javax.swing.JLabel RecyclingServiceInfo3;
    private javax.swing.JLabel RecyclingServiceInfo4;
    private javax.swing.JLabel RecyclingServiceInfo5;
    private javax.swing.JLabel RecyclingServiceInfo6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton noBtn;
    private javax.swing.JButton yesBtn;
    // End of variables declaration//GEN-END:variables
}
