/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recyclingapp;

import java.awt.Color;

/**
 *
 * @author davog
 */
public class RecyclingListGUI extends javax.swing.JFrame {

    /**
     * Creates new form RecyclingListGUI
     */
    public RecyclingListGUI() {
        initComponents();
        getContentPane().setBackground(new Color(30,30,30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Obj1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        ImgPanel = new javax.swing.JPanel();
        Description = new javax.swing.JLabel();
        MaterialsLbl = new javax.swing.JLabel();
        Recyclable = new javax.swing.JLabel();
        EILbl = new javax.swing.JLabel();
        MaterialsCB = new javax.swing.JComboBox<>();
        DTLbl = new javax.swing.JLabel();
        DT = new javax.swing.JLabel();
        RTLbl = new javax.swing.JLabel();
        RT = new javax.swing.JLabel();
        EI = new javax.swing.JLabel();
        Obj2 = new javax.swing.JPanel();
        Name3 = new javax.swing.JLabel();
        Type3 = new javax.swing.JLabel();
        ImgPanel3 = new javax.swing.JPanel();
        Description2 = new javax.swing.JLabel();
        MaterialsLbl2 = new javax.swing.JLabel();
        Recyclable2 = new javax.swing.JLabel();
        EILbl2 = new javax.swing.JLabel();
        MaterialsCB2 = new javax.swing.JComboBox<>();
        DTLbl2 = new javax.swing.JLabel();
        DT2 = new javax.swing.JLabel();
        RTLbl2 = new javax.swing.JLabel();
        RT2 = new javax.swing.JLabel();
        EI2 = new javax.swing.JLabel();
        Obj3 = new javax.swing.JPanel();
        Name4 = new javax.swing.JLabel();
        Type4 = new javax.swing.JLabel();
        ImgPanel4 = new javax.swing.JPanel();
        Description3 = new javax.swing.JLabel();
        MaterialsLbl3 = new javax.swing.JLabel();
        Recyclable3 = new javax.swing.JLabel();
        EILbl3 = new javax.swing.JLabel();
        MaterialsCB3 = new javax.swing.JComboBox<>();
        DTLbl3 = new javax.swing.JLabel();
        DT3 = new javax.swing.JLabel();
        RTLbl3 = new javax.swing.JLabel();
        RT3 = new javax.swing.JLabel();
        EI3 = new javax.swing.JLabel();
        Obj4 = new javax.swing.JPanel();
        Name2 = new javax.swing.JLabel();
        Type2 = new javax.swing.JLabel();
        ImgPanel2 = new javax.swing.JPanel();
        Description1 = new javax.swing.JLabel();
        MaterialsLbl1 = new javax.swing.JLabel();
        Recyclable1 = new javax.swing.JLabel();
        EILbl1 = new javax.swing.JLabel();
        MaterialsCB1 = new javax.swing.JComboBox<>();
        DTLbl1 = new javax.swing.JLabel();
        DT1 = new javax.swing.JLabel();
        RTLbl1 = new javax.swing.JLabel();
        RT1 = new javax.swing.JLabel();
        EI1 = new javax.swing.JLabel();
        Obj5 = new javax.swing.JPanel();
        Name5 = new javax.swing.JLabel();
        Type5 = new javax.swing.JLabel();
        ImgPanel5 = new javax.swing.JPanel();
        Description4 = new javax.swing.JLabel();
        MaterialsLbl4 = new javax.swing.JLabel();
        Recyclable4 = new javax.swing.JLabel();
        EILbl4 = new javax.swing.JLabel();
        MaterialsCB4 = new javax.swing.JComboBox<>();
        DTLbl4 = new javax.swing.JLabel();
        DT4 = new javax.swing.JLabel();
        RTLbl4 = new javax.swing.JLabel();
        RT4 = new javax.swing.JLabel();
        EI4 = new javax.swing.JLabel();
        Obj6 = new javax.swing.JPanel();
        Name6 = new javax.swing.JLabel();
        Type6 = new javax.swing.JLabel();
        ImgPanel6 = new javax.swing.JPanel();
        Description5 = new javax.swing.JLabel();
        MaterialsLbl5 = new javax.swing.JLabel();
        Recyclable5 = new javax.swing.JLabel();
        EILbl5 = new javax.swing.JLabel();
        MaterialsCB5 = new javax.swing.JComboBox<>();
        DTLbl5 = new javax.swing.JLabel();
        DT5 = new javax.swing.JLabel();
        RTLbl5 = new javax.swing.JLabel();
        RT5 = new javax.swing.JLabel();
        EI5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));

        SearchField.setBackground(new java.awt.Color(102, 204, 255));
        SearchField.setText("Search");

        SearchBtn.setBackground(new java.awt.Color(102, 204, 255));
        SearchBtn.setText("⌕");
        SearchBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(102, 204, 255));
        BackBtn.setText("⇐");
        BackBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        scrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        scrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setOpaque(false);

        Obj1.setBackground(new java.awt.Color(102, 204, 255));

        Name.setBackground(new java.awt.Color(0, 175, 255));
        Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Name");
        Name.setOpaque(true);

        Type.setBackground(new java.awt.Color(0, 175, 255));
        Type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type.setText("Type");
        Type.setOpaque(true);

        ImgPanel.setBackground(new java.awt.Color(0, 175, 255));

        javax.swing.GroupLayout ImgPanelLayout = new javax.swing.GroupLayout(ImgPanel);
        ImgPanel.setLayout(ImgPanelLayout);
        ImgPanelLayout.setHorizontalGroup(
            ImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        ImgPanelLayout.setVerticalGroup(
            ImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Description.setBackground(new java.awt.Color(0, 175, 255));
        Description.setText("Description");
        Description.setOpaque(true);

        MaterialsLbl.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaterialsLbl.setText("Materials");
        MaterialsLbl.setOpaque(true);

        Recyclable.setBackground(new java.awt.Color(0, 175, 255));
        Recyclable.setText("recyclable");
        Recyclable.setOpaque(true);

        EILbl.setBackground(new java.awt.Color(0, 175, 255));
        EILbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EILbl.setText("<html>           <p>Enviromental Impact</p> </html>");
        EILbl.setOpaque(true);

        MaterialsCB.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper" }));

        DTLbl.setBackground(new java.awt.Color(0, 175, 255));
        DTLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DTLbl.setText("<html>\n          <p>Decomposition Time</p>\n</html>");
        DTLbl.setOpaque(true);

        DT.setBackground(new java.awt.Color(0, 175, 255));
        DT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DT.setText("10 years");
        DT.setOpaque(true);

        RTLbl.setBackground(new java.awt.Color(0, 175, 255));
        RTLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RTLbl.setText("<html>           <p>Recycling Type</p> </html>");
        RTLbl.setOpaque(true);

        RT.setBackground(new java.awt.Color(0, 175, 255));
        RT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RT.setText("Plastic");
        RT.setOpaque(true);

        EI.setBackground(new java.awt.Color(0, 175, 255));
        EI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EI.setText("9/10");
        EI.setOpaque(true);

        javax.swing.GroupLayout Obj1Layout = new javax.swing.GroupLayout(Obj1);
        Obj1.setLayout(Obj1Layout);
        Obj1Layout.setHorizontalGroup(
            Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj1Layout.createSequentialGroup()
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recyclable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj1Layout.createSequentialGroup()
                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj1Layout.createSequentialGroup()
                        .addComponent(ImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EILbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(DTLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RTLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addComponent(MaterialsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialsCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Obj1Layout.setVerticalGroup(
            Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj1Layout.createSequentialGroup()
                        .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialsCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EILbl, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(EI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(ImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recyclable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj2.setBackground(new java.awt.Color(102, 204, 255));

        Name3.setBackground(new java.awt.Color(0, 175, 255));
        Name3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name3.setText("Name");
        Name3.setOpaque(true);

        Type3.setBackground(new java.awt.Color(0, 175, 255));
        Type3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Type3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type3.setText("Type");
        Type3.setOpaque(true);

        ImgPanel3.setBackground(new java.awt.Color(0, 175, 255));

        javax.swing.GroupLayout ImgPanel3Layout = new javax.swing.GroupLayout(ImgPanel3);
        ImgPanel3.setLayout(ImgPanel3Layout);
        ImgPanel3Layout.setHorizontalGroup(
            ImgPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        ImgPanel3Layout.setVerticalGroup(
            ImgPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Description2.setBackground(new java.awt.Color(0, 175, 255));
        Description2.setText("Description");
        Description2.setOpaque(true);

        MaterialsLbl2.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaterialsLbl2.setText("Materials");
        MaterialsLbl2.setOpaque(true);

        Recyclable2.setBackground(new java.awt.Color(0, 175, 255));
        Recyclable2.setText("recyclable");
        Recyclable2.setOpaque(true);

        EILbl2.setBackground(new java.awt.Color(0, 175, 255));
        EILbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EILbl2.setText("<html>           <p>Enviromental Impact</p> </html>");
        EILbl2.setOpaque(true);

        MaterialsCB2.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper" }));

        DTLbl2.setBackground(new java.awt.Color(0, 175, 255));
        DTLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DTLbl2.setText("<html>\n          <p>Decomposition Time</p>\n</html>");
        DTLbl2.setOpaque(true);

        DT2.setBackground(new java.awt.Color(0, 175, 255));
        DT2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DT2.setText("10 years");
        DT2.setOpaque(true);

        RTLbl2.setBackground(new java.awt.Color(0, 175, 255));
        RTLbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RTLbl2.setText("<html>           <p>Recycling Type</p> </html>");
        RTLbl2.setOpaque(true);

        RT2.setBackground(new java.awt.Color(0, 175, 255));
        RT2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RT2.setText("Plastic");
        RT2.setOpaque(true);

        EI2.setBackground(new java.awt.Color(0, 175, 255));
        EI2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EI2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EI2.setText("9/10");
        EI2.setOpaque(true);

        javax.swing.GroupLayout Obj2Layout = new javax.swing.GroupLayout(Obj2);
        Obj2.setLayout(Obj2Layout);
        Obj2Layout.setHorizontalGroup(
            Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj2Layout.createSequentialGroup()
                        .addComponent(Description2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recyclable2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj2Layout.createSequentialGroup()
                        .addComponent(Name3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj2Layout.createSequentialGroup()
                        .addComponent(ImgPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EILbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(DTLbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RTLbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addComponent(MaterialsLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialsCB2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EI2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Obj2Layout.setVerticalGroup(
            Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name3)
                    .addComponent(Type3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj2Layout.createSequentialGroup()
                        .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialsLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialsCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DT2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RT2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EI2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EILbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                    .addComponent(ImgPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recyclable2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj3.setBackground(new java.awt.Color(102, 204, 255));

        Name4.setBackground(new java.awt.Color(0, 175, 255));
        Name4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name4.setText("Name");
        Name4.setOpaque(true);

        Type4.setBackground(new java.awt.Color(0, 175, 255));
        Type4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Type4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type4.setText("Type");
        Type4.setOpaque(true);

        ImgPanel4.setBackground(new java.awt.Color(0, 175, 255));

        javax.swing.GroupLayout ImgPanel4Layout = new javax.swing.GroupLayout(ImgPanel4);
        ImgPanel4.setLayout(ImgPanel4Layout);
        ImgPanel4Layout.setHorizontalGroup(
            ImgPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        ImgPanel4Layout.setVerticalGroup(
            ImgPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        Description3.setBackground(new java.awt.Color(0, 175, 255));
        Description3.setText("Description");
        Description3.setOpaque(true);

        MaterialsLbl3.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsLbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaterialsLbl3.setText("Materials");
        MaterialsLbl3.setOpaque(true);

        Recyclable3.setBackground(new java.awt.Color(0, 175, 255));
        Recyclable3.setText("recyclable");
        Recyclable3.setOpaque(true);

        EILbl3.setBackground(new java.awt.Color(0, 175, 255));
        EILbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EILbl3.setText("<html>           <p>Enviromental Impact</p> </html>");
        EILbl3.setOpaque(true);

        MaterialsCB3.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper" }));

        DTLbl3.setBackground(new java.awt.Color(0, 175, 255));
        DTLbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DTLbl3.setText("<html>\n          <p>Decomposition Time</p>\n</html>");
        DTLbl3.setOpaque(true);

        DT3.setBackground(new java.awt.Color(0, 175, 255));
        DT3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DT3.setText("10 years");
        DT3.setOpaque(true);

        RTLbl3.setBackground(new java.awt.Color(0, 175, 255));
        RTLbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RTLbl3.setText("<html>           <p>Recycling Type</p> </html>");
        RTLbl3.setOpaque(true);

        RT3.setBackground(new java.awt.Color(0, 175, 255));
        RT3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RT3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RT3.setText("Plastic");
        RT3.setOpaque(true);

        EI3.setBackground(new java.awt.Color(0, 175, 255));
        EI3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EI3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EI3.setText("9/10");
        EI3.setOpaque(true);

        javax.swing.GroupLayout Obj3Layout = new javax.swing.GroupLayout(Obj3);
        Obj3.setLayout(Obj3Layout);
        Obj3Layout.setHorizontalGroup(
            Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj3Layout.createSequentialGroup()
                        .addComponent(Description3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recyclable3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj3Layout.createSequentialGroup()
                        .addComponent(Name4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj3Layout.createSequentialGroup()
                        .addComponent(ImgPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EILbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(DTLbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RTLbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addComponent(MaterialsLbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialsCB3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EI3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Obj3Layout.setVerticalGroup(
            Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name4)
                    .addComponent(Type4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Obj3Layout.createSequentialGroup()
                        .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialsLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialsCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DT3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RT3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EI3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EILbl3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                    .addComponent(ImgPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recyclable3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj4.setBackground(new java.awt.Color(102, 204, 255));

        Name2.setBackground(new java.awt.Color(0, 175, 255));
        Name2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name2.setText("Name");
        Name2.setOpaque(true);

        Type2.setBackground(new java.awt.Color(0, 175, 255));
        Type2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Type2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type2.setText("Type");
        Type2.setOpaque(true);

        ImgPanel2.setBackground(new java.awt.Color(0, 175, 255));

        javax.swing.GroupLayout ImgPanel2Layout = new javax.swing.GroupLayout(ImgPanel2);
        ImgPanel2.setLayout(ImgPanel2Layout);
        ImgPanel2Layout.setHorizontalGroup(
            ImgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        ImgPanel2Layout.setVerticalGroup(
            ImgPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Description1.setBackground(new java.awt.Color(0, 175, 255));
        Description1.setText("Description");
        Description1.setOpaque(true);

        MaterialsLbl1.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaterialsLbl1.setText("Materials");
        MaterialsLbl1.setOpaque(true);

        Recyclable1.setBackground(new java.awt.Color(0, 175, 255));
        Recyclable1.setText("recyclable");
        Recyclable1.setOpaque(true);

        EILbl1.setBackground(new java.awt.Color(0, 175, 255));
        EILbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EILbl1.setText("<html>           <p>Enviromental Impact</p> </html>");
        EILbl1.setOpaque(true);

        MaterialsCB1.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper" }));

        DTLbl1.setBackground(new java.awt.Color(0, 175, 255));
        DTLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DTLbl1.setText("<html>\n          <p>Decomposition Time</p>\n</html>");
        DTLbl1.setOpaque(true);

        DT1.setBackground(new java.awt.Color(0, 175, 255));
        DT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DT1.setText("10 years");
        DT1.setOpaque(true);

        RTLbl1.setBackground(new java.awt.Color(0, 175, 255));
        RTLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RTLbl1.setText("<html>           <p>Recycling Type</p> </html>");
        RTLbl1.setOpaque(true);

        RT1.setBackground(new java.awt.Color(0, 175, 255));
        RT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RT1.setText("Plastic");
        RT1.setOpaque(true);

        EI1.setBackground(new java.awt.Color(0, 175, 255));
        EI1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EI1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EI1.setText("9/10");
        EI1.setOpaque(true);

        javax.swing.GroupLayout Obj4Layout = new javax.swing.GroupLayout(Obj4);
        Obj4.setLayout(Obj4Layout);
        Obj4Layout.setHorizontalGroup(
            Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj4Layout.createSequentialGroup()
                        .addComponent(Description1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recyclable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj4Layout.createSequentialGroup()
                        .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj4Layout.createSequentialGroup()
                        .addComponent(ImgPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EILbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(DTLbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RTLbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addComponent(MaterialsLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialsCB1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Obj4Layout.setVerticalGroup(
            Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name2)
                    .addComponent(Type2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj4Layout.createSequentialGroup()
                        .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialsLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialsCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DT1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RT1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EI1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EILbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                    .addComponent(ImgPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recyclable1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj5.setBackground(new java.awt.Color(102, 204, 255));

        Name5.setBackground(new java.awt.Color(0, 175, 255));
        Name5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name5.setText("Name");
        Name5.setOpaque(true);

        Type5.setBackground(new java.awt.Color(0, 175, 255));
        Type5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Type5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type5.setText("Type");
        Type5.setOpaque(true);

        ImgPanel5.setBackground(new java.awt.Color(0, 175, 255));

        javax.swing.GroupLayout ImgPanel5Layout = new javax.swing.GroupLayout(ImgPanel5);
        ImgPanel5.setLayout(ImgPanel5Layout);
        ImgPanel5Layout.setHorizontalGroup(
            ImgPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        ImgPanel5Layout.setVerticalGroup(
            ImgPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        Description4.setBackground(new java.awt.Color(0, 175, 255));
        Description4.setText("Description");
        Description4.setOpaque(true);

        MaterialsLbl4.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsLbl4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaterialsLbl4.setText("Materials");
        MaterialsLbl4.setOpaque(true);

        Recyclable4.setBackground(new java.awt.Color(0, 175, 255));
        Recyclable4.setText("recyclable");
        Recyclable4.setOpaque(true);

        EILbl4.setBackground(new java.awt.Color(0, 175, 255));
        EILbl4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EILbl4.setText("<html>           <p>Enviromental Impact</p> </html>");
        EILbl4.setOpaque(true);

        MaterialsCB4.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsCB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper" }));

        DTLbl4.setBackground(new java.awt.Color(0, 175, 255));
        DTLbl4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DTLbl4.setText("<html>\n          <p>Decomposition Time</p>\n</html>");
        DTLbl4.setOpaque(true);

        DT4.setBackground(new java.awt.Color(0, 175, 255));
        DT4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DT4.setText("10 years");
        DT4.setOpaque(true);

        RTLbl4.setBackground(new java.awt.Color(0, 175, 255));
        RTLbl4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RTLbl4.setText("<html>           <p>Recycling Type</p> </html>");
        RTLbl4.setOpaque(true);

        RT4.setBackground(new java.awt.Color(0, 175, 255));
        RT4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RT4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RT4.setText("Plastic");
        RT4.setOpaque(true);

        EI4.setBackground(new java.awt.Color(0, 175, 255));
        EI4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EI4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EI4.setText("9/10");
        EI4.setOpaque(true);

        javax.swing.GroupLayout Obj5Layout = new javax.swing.GroupLayout(Obj5);
        Obj5.setLayout(Obj5Layout);
        Obj5Layout.setHorizontalGroup(
            Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj5Layout.createSequentialGroup()
                        .addComponent(Description4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recyclable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj5Layout.createSequentialGroup()
                        .addComponent(Name5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj5Layout.createSequentialGroup()
                        .addComponent(ImgPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EILbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(DTLbl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RTLbl4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addComponent(MaterialsLbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialsCB4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EI4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Obj5Layout.setVerticalGroup(
            Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name5)
                    .addComponent(Type5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Obj5Layout.createSequentialGroup()
                        .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialsLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialsCB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DT4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RT4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EI4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EILbl4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                    .addComponent(ImgPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recyclable4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Obj6.setBackground(new java.awt.Color(102, 204, 255));

        Name6.setBackground(new java.awt.Color(0, 175, 255));
        Name6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name6.setText("Name");
        Name6.setOpaque(true);

        Type6.setBackground(new java.awt.Color(0, 175, 255));
        Type6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Type6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Type6.setText("Type");
        Type6.setOpaque(true);

        ImgPanel6.setBackground(new java.awt.Color(0, 175, 255));

        javax.swing.GroupLayout ImgPanel6Layout = new javax.swing.GroupLayout(ImgPanel6);
        ImgPanel6.setLayout(ImgPanel6Layout);
        ImgPanel6Layout.setHorizontalGroup(
            ImgPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );
        ImgPanel6Layout.setVerticalGroup(
            ImgPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        Description5.setBackground(new java.awt.Color(0, 175, 255));
        Description5.setText("Description");
        Description5.setOpaque(true);

        MaterialsLbl5.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsLbl5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaterialsLbl5.setText("Materials");
        MaterialsLbl5.setOpaque(true);

        Recyclable5.setBackground(new java.awt.Color(0, 175, 255));
        Recyclable5.setText("recyclable");
        Recyclable5.setOpaque(true);

        EILbl5.setBackground(new java.awt.Color(0, 175, 255));
        EILbl5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EILbl5.setText("<html>           <p>Enviromental Impact</p> </html>");
        EILbl5.setOpaque(true);

        MaterialsCB5.setBackground(new java.awt.Color(0, 175, 255));
        MaterialsCB5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plastic", "Paper" }));

        DTLbl5.setBackground(new java.awt.Color(0, 175, 255));
        DTLbl5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DTLbl5.setText("<html>\n          <p>Decomposition Time</p>\n</html>");
        DTLbl5.setOpaque(true);

        DT5.setBackground(new java.awt.Color(0, 175, 255));
        DT5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DT5.setText("10 years");
        DT5.setOpaque(true);

        RTLbl5.setBackground(new java.awt.Color(0, 175, 255));
        RTLbl5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RTLbl5.setText("<html>           <p>Recycling Type</p> </html>");
        RTLbl5.setOpaque(true);

        RT5.setBackground(new java.awt.Color(0, 175, 255));
        RT5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RT5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RT5.setText("Plastic");
        RT5.setOpaque(true);

        EI5.setBackground(new java.awt.Color(0, 175, 255));
        EI5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EI5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EI5.setText("9/10");
        EI5.setOpaque(true);

        javax.swing.GroupLayout Obj6Layout = new javax.swing.GroupLayout(Obj6);
        Obj6.setLayout(Obj6Layout);
        Obj6Layout.setHorizontalGroup(
            Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Obj6Layout.createSequentialGroup()
                        .addComponent(Description5, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Recyclable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj6Layout.createSequentialGroup()
                        .addComponent(Name6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Obj6Layout.createSequentialGroup()
                        .addComponent(ImgPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(EILbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(DTLbl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(RTLbl5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                            .addComponent(MaterialsLbl5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaterialsCB5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DT5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RT5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EI5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Obj6Layout.setVerticalGroup(
            Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Obj6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name6)
                    .addComponent(Type6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Obj6Layout.createSequentialGroup()
                        .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaterialsLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaterialsCB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DT5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DTLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RTLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RT5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EI5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EILbl5, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                    .addComponent(ImgPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Obj6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Recyclable5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Obj6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Obj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Obj4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Obj3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Obj5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Obj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Obj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Obj4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Obj5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Obj3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Obj6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Obj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        scrollPane1.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 175, 255));
        jLabel1.setText("Recycling Object List");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recyclingapp/icons/home.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recyclingapp/icons/test.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(639, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecyclingListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecyclingListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecyclingListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecyclingListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecyclingListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel DT;
    private javax.swing.JLabel DT1;
    private javax.swing.JLabel DT2;
    private javax.swing.JLabel DT3;
    private javax.swing.JLabel DT4;
    private javax.swing.JLabel DT5;
    private javax.swing.JLabel DTLbl;
    private javax.swing.JLabel DTLbl1;
    private javax.swing.JLabel DTLbl2;
    private javax.swing.JLabel DTLbl3;
    private javax.swing.JLabel DTLbl4;
    private javax.swing.JLabel DTLbl5;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Description1;
    private javax.swing.JLabel Description2;
    private javax.swing.JLabel Description3;
    private javax.swing.JLabel Description4;
    private javax.swing.JLabel Description5;
    private javax.swing.JLabel EI;
    private javax.swing.JLabel EI1;
    private javax.swing.JLabel EI2;
    private javax.swing.JLabel EI3;
    private javax.swing.JLabel EI4;
    private javax.swing.JLabel EI5;
    private javax.swing.JLabel EILbl;
    private javax.swing.JLabel EILbl1;
    private javax.swing.JLabel EILbl2;
    private javax.swing.JLabel EILbl3;
    private javax.swing.JLabel EILbl4;
    private javax.swing.JLabel EILbl5;
    private javax.swing.JPanel ImgPanel;
    private javax.swing.JPanel ImgPanel2;
    private javax.swing.JPanel ImgPanel3;
    private javax.swing.JPanel ImgPanel4;
    private javax.swing.JPanel ImgPanel5;
    private javax.swing.JPanel ImgPanel6;
    private javax.swing.JComboBox<String> MaterialsCB;
    private javax.swing.JComboBox<String> MaterialsCB1;
    private javax.swing.JComboBox<String> MaterialsCB2;
    private javax.swing.JComboBox<String> MaterialsCB3;
    private javax.swing.JComboBox<String> MaterialsCB4;
    private javax.swing.JComboBox<String> MaterialsCB5;
    private javax.swing.JLabel MaterialsLbl;
    private javax.swing.JLabel MaterialsLbl1;
    private javax.swing.JLabel MaterialsLbl2;
    private javax.swing.JLabel MaterialsLbl3;
    private javax.swing.JLabel MaterialsLbl4;
    private javax.swing.JLabel MaterialsLbl5;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JPanel Obj1;
    private javax.swing.JPanel Obj2;
    private javax.swing.JPanel Obj3;
    private javax.swing.JPanel Obj4;
    private javax.swing.JPanel Obj5;
    private javax.swing.JPanel Obj6;
    private javax.swing.JLabel RT;
    private javax.swing.JLabel RT1;
    private javax.swing.JLabel RT2;
    private javax.swing.JLabel RT3;
    private javax.swing.JLabel RT4;
    private javax.swing.JLabel RT5;
    private javax.swing.JLabel RTLbl;
    private javax.swing.JLabel RTLbl1;
    private javax.swing.JLabel RTLbl2;
    private javax.swing.JLabel RTLbl3;
    private javax.swing.JLabel RTLbl4;
    private javax.swing.JLabel RTLbl5;
    private javax.swing.JLabel Recyclable;
    private javax.swing.JLabel Recyclable1;
    private javax.swing.JLabel Recyclable2;
    private javax.swing.JLabel Recyclable3;
    private javax.swing.JLabel Recyclable4;
    private javax.swing.JLabel Recyclable5;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchField;
    private javax.swing.JLabel Type;
    private javax.swing.JLabel Type2;
    private javax.swing.JLabel Type3;
    private javax.swing.JLabel Type4;
    private javax.swing.JLabel Type5;
    private javax.swing.JLabel Type6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
